// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.ruoyi.platform.grpc;

/**
 * Protobuf type {@code proto.TeacheraccResponse}
 */
public final class TeacheraccResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.TeacheraccResponse)
    TeacheraccResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TeacheraccResponse.newBuilder() to construct.
  private TeacheraccResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TeacheraccResponse() {
    step_ = emptyIntList();
    maxacc_ = emptyDoubleList();
    minacc_ = emptyDoubleList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TeacheraccResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TeacheraccResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              step_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            step_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              step_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              step_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 17: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              maxacc_ = newDoubleList();
              mutable_bitField0_ |= 0x00000002;
            }
            maxacc_.addDouble(input.readDouble());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              maxacc_ = newDoubleList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              maxacc_.addDouble(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 25: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              minacc_ = newDoubleList();
              mutable_bitField0_ |= 0x00000004;
            }
            minacc_.addDouble(input.readDouble());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              minacc_ = newDoubleList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              minacc_.addDouble(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        step_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        maxacc_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        minacc_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TrainProto.internal_static_proto_TeacheraccResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TrainProto.internal_static_proto_TeacheraccResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TeacheraccResponse.class, Builder.class);
  }

  public static final int STEP_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList step_;
  /**
   * <code>repeated int32 step = 1;</code>
   * @return A list containing the step.
   */
  @Override
  public java.util.List<Integer>
      getStepList() {
    return step_;
  }
  /**
   * <code>repeated int32 step = 1;</code>
   * @return The count of step.
   */
  public int getStepCount() {
    return step_.size();
  }
  /**
   * <code>repeated int32 step = 1;</code>
   * @param index The index of the element to return.
   * @return The step at the given index.
   */
  public int getStep(int index) {
    return step_.getInt(index);
  }
  private int stepMemoizedSerializedSize = -1;

  public static final int MAXACC_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.DoubleList maxacc_;
  /**
   * <code>repeated double maxacc = 2;</code>
   * @return A list containing the maxacc.
   */
  @Override
  public java.util.List<Double>
      getMaxaccList() {
    return maxacc_;
  }
  /**
   * <code>repeated double maxacc = 2;</code>
   * @return The count of maxacc.
   */
  public int getMaxaccCount() {
    return maxacc_.size();
  }
  /**
   * <code>repeated double maxacc = 2;</code>
   * @param index The index of the element to return.
   * @return The maxacc at the given index.
   */
  public double getMaxacc(int index) {
    return maxacc_.getDouble(index);
  }
  private int maxaccMemoizedSerializedSize = -1;

  public static final int MINACC_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.DoubleList minacc_;
  /**
   * <code>repeated double minacc = 3;</code>
   * @return A list containing the minacc.
   */
  @Override
  public java.util.List<Double>
      getMinaccList() {
    return minacc_;
  }
  /**
   * <code>repeated double minacc = 3;</code>
   * @return The count of minacc.
   */
  public int getMinaccCount() {
    return minacc_.size();
  }
  /**
   * <code>repeated double minacc = 3;</code>
   * @param index The index of the element to return.
   * @return The minacc at the given index.
   */
  public double getMinacc(int index) {
    return minacc_.getDouble(index);
  }
  private int minaccMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getStepList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(stepMemoizedSerializedSize);
    }
    for (int i = 0; i < step_.size(); i++) {
      output.writeInt32NoTag(step_.getInt(i));
    }
    if (getMaxaccList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(maxaccMemoizedSerializedSize);
    }
    for (int i = 0; i < maxacc_.size(); i++) {
      output.writeDoubleNoTag(maxacc_.getDouble(i));
    }
    if (getMinaccList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(minaccMemoizedSerializedSize);
    }
    for (int i = 0; i < minacc_.size(); i++) {
      output.writeDoubleNoTag(minacc_.getDouble(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < step_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(step_.getInt(i));
      }
      size += dataSize;
      if (!getStepList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      stepMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 8 * getMaxaccList().size();
      size += dataSize;
      if (!getMaxaccList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      maxaccMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 8 * getMinaccList().size();
      size += dataSize;
      if (!getMinaccList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      minaccMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TeacheraccResponse)) {
      return super.equals(obj);
    }
    TeacheraccResponse other = (TeacheraccResponse) obj;

    if (!getStepList()
        .equals(other.getStepList())) return false;
    if (!getMaxaccList()
        .equals(other.getMaxaccList())) return false;
    if (!getMinaccList()
        .equals(other.getMinaccList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStepCount() > 0) {
      hash = (37 * hash) + STEP_FIELD_NUMBER;
      hash = (53 * hash) + getStepList().hashCode();
    }
    if (getMaxaccCount() > 0) {
      hash = (37 * hash) + MAXACC_FIELD_NUMBER;
      hash = (53 * hash) + getMaxaccList().hashCode();
    }
    if (getMinaccCount() > 0) {
      hash = (37 * hash) + MINACC_FIELD_NUMBER;
      hash = (53 * hash) + getMinaccList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TeacheraccResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TeacheraccResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TeacheraccResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TeacheraccResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TeacheraccResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TeacheraccResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TeacheraccResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TeacheraccResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TeacheraccResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TeacheraccResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TeacheraccResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TeacheraccResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeacheraccResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.TeacheraccResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.TeacheraccResponse)
      TeacheraccResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TrainProto.internal_static_proto_TeacheraccResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TrainProto.internal_static_proto_TeacheraccResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeacheraccResponse.class, Builder.class);
    }

    // Construct using com.ruoyi.platform.grpc.TeacheraccResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      step_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      maxacc_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000002);
      minacc_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TrainProto.internal_static_proto_TeacheraccResponse_descriptor;
    }

    @Override
    public TeacheraccResponse getDefaultInstanceForType() {
      return TeacheraccResponse.getDefaultInstance();
    }

    @Override
    public TeacheraccResponse build() {
      TeacheraccResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TeacheraccResponse buildPartial() {
      TeacheraccResponse result = new TeacheraccResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        step_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.step_ = step_;
      if (((bitField0_ & 0x00000002) != 0)) {
        maxacc_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.maxacc_ = maxacc_;
      if (((bitField0_ & 0x00000004) != 0)) {
        minacc_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.minacc_ = minacc_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TeacheraccResponse) {
        return mergeFrom((TeacheraccResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TeacheraccResponse other) {
      if (other == TeacheraccResponse.getDefaultInstance()) return this;
      if (!other.step_.isEmpty()) {
        if (step_.isEmpty()) {
          step_ = other.step_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureStepIsMutable();
          step_.addAll(other.step_);
        }
        onChanged();
      }
      if (!other.maxacc_.isEmpty()) {
        if (maxacc_.isEmpty()) {
          maxacc_ = other.maxacc_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureMaxaccIsMutable();
          maxacc_.addAll(other.maxacc_);
        }
        onChanged();
      }
      if (!other.minacc_.isEmpty()) {
        if (minacc_.isEmpty()) {
          minacc_ = other.minacc_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureMinaccIsMutable();
          minacc_.addAll(other.minacc_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TeacheraccResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TeacheraccResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList step_ = emptyIntList();
    private void ensureStepIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        step_ = mutableCopy(step_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @return A list containing the step.
     */
    public java.util.List<Integer>
        getStepList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(step_) : step_;
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @return The count of step.
     */
    public int getStepCount() {
      return step_.size();
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @param index The index of the element to return.
     * @return The step at the given index.
     */
    public int getStep(int index) {
      return step_.getInt(index);
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @param index The index to set the value at.
     * @param value The step to set.
     * @return This builder for chaining.
     */
    public Builder setStep(
        int index, int value) {
      ensureStepIsMutable();
      step_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @param value The step to add.
     * @return This builder for chaining.
     */
    public Builder addStep(int value) {
      ensureStepIsMutable();
      step_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @param values The step to add.
     * @return This builder for chaining.
     */
    public Builder addAllStep(
        Iterable<? extends Integer> values) {
      ensureStepIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, step_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 step = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStep() {
      step_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList maxacc_ = emptyDoubleList();
    private void ensureMaxaccIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        maxacc_ = mutableCopy(maxacc_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @return A list containing the maxacc.
     */
    public java.util.List<Double>
        getMaxaccList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(maxacc_) : maxacc_;
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @return The count of maxacc.
     */
    public int getMaxaccCount() {
      return maxacc_.size();
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @param index The index of the element to return.
     * @return The maxacc at the given index.
     */
    public double getMaxacc(int index) {
      return maxacc_.getDouble(index);
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @param index The index to set the value at.
     * @param value The maxacc to set.
     * @return This builder for chaining.
     */
    public Builder setMaxacc(
        int index, double value) {
      ensureMaxaccIsMutable();
      maxacc_.setDouble(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @param value The maxacc to add.
     * @return This builder for chaining.
     */
    public Builder addMaxacc(double value) {
      ensureMaxaccIsMutable();
      maxacc_.addDouble(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @param values The maxacc to add.
     * @return This builder for chaining.
     */
    public Builder addAllMaxacc(
        Iterable<? extends Double> values) {
      ensureMaxaccIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, maxacc_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double maxacc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxacc() {
      maxacc_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList minacc_ = emptyDoubleList();
    private void ensureMinaccIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        minacc_ = mutableCopy(minacc_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @return A list containing the minacc.
     */
    public java.util.List<Double>
        getMinaccList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(minacc_) : minacc_;
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @return The count of minacc.
     */
    public int getMinaccCount() {
      return minacc_.size();
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @param index The index of the element to return.
     * @return The minacc at the given index.
     */
    public double getMinacc(int index) {
      return minacc_.getDouble(index);
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @param index The index to set the value at.
     * @param value The minacc to set.
     * @return This builder for chaining.
     */
    public Builder setMinacc(
        int index, double value) {
      ensureMinaccIsMutable();
      minacc_.setDouble(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @param value The minacc to add.
     * @return This builder for chaining.
     */
    public Builder addMinacc(double value) {
      ensureMinaccIsMutable();
      minacc_.addDouble(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @param values The minacc to add.
     * @return This builder for chaining.
     */
    public Builder addAllMinacc(
        Iterable<? extends Double> values) {
      ensureMinaccIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, minacc_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double minacc = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinacc() {
      minacc_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.TeacheraccResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.TeacheraccResponse)
  private static final TeacheraccResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeacheraccResponse();
  }

  public static TeacheraccResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TeacheraccResponse>
      PARSER = new com.google.protobuf.AbstractParser<TeacheraccResponse>() {
    @Override
    public TeacheraccResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TeacheraccResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TeacheraccResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TeacheraccResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public TeacheraccResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

