// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.ruoyi.platform.grpc;

public interface TeacheraccResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TeacheraccResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 step = 1;</code>
   * @return A list containing the step.
   */
  java.util.List<Integer> getStepList();
  /**
   * <code>repeated int32 step = 1;</code>
   * @return The count of step.
   */
  int getStepCount();
  /**
   * <code>repeated int32 step = 1;</code>
   * @param index The index of the element to return.
   * @return The step at the given index.
   */
  int getStep(int index);

  /**
   * <code>repeated double maxacc = 2;</code>
   * @return A list containing the maxacc.
   */
  java.util.List<Double> getMaxaccList();
  /**
   * <code>repeated double maxacc = 2;</code>
   * @return The count of maxacc.
   */
  int getMaxaccCount();
  /**
   * <code>repeated double maxacc = 2;</code>
   * @param index The index of the element to return.
   * @return The maxacc at the given index.
   */
  double getMaxacc(int index);

  /**
   * <code>repeated double minacc = 3;</code>
   * @return A list containing the minacc.
   */
  java.util.List<Double> getMinaccList();
  /**
   * <code>repeated double minacc = 3;</code>
   * @return The count of minacc.
   */
  int getMinaccCount();
  /**
   * <code>repeated double minacc = 3;</code>
   * @param index The index of the element to return.
   * @return The minacc at the given index.
   */
  double getMinacc(int index);
}
