// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: train.proto

package com.ruoyi.platform.grpc;

public final class TrainProto {
  private TrainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_WlossRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_WlossRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TeacheraccRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TeacheraccRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StepResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StepResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_WlossResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_WlossResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TeacheraccResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TeacheraccResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013train.proto\022\005proto\"\032\n\014WlossRequest\022\n\n\002" +
      "id\030\001 \001(\005\"\031\n\013StepRequest\022\n\n\002id\030\001 \001(\005\"\037\n\021T" +
      "eacheraccRequest\022\n\n\002id\030\001 \001(\005\"\034\n\014StepResp" +
      "onse\022\014\n\004step\030\001 \003(\005\",\n\rWlossResponse\022\014\n\004s" +
      "tep\030\001 \003(\005\022\r\n\005wloss\030\002 \003(\001\"B\n\022TeacheraccRe" +
      "sponse\022\014\n\004step\030\001 \003(\005\022\016\n\006maxacc\030\002 \003(\001\022\016\n\006" +
      "minacc\030\003 \003(\0012\270\001\n\005Train\0222\n\007GetStep\022\022.prot" +
      "o.StepRequest\032\023.proto.StepResponse\0225\n\010Ge" +
      "tWloss\022\023.proto.WlossRequest\032\024.proto.Wlos" +
      "sResponse\022D\n\rGetTeacheracc\022\030.proto.Teach" +
      "eraccRequest\032\031.proto.TeacheraccResponseB" +
      "-\n\027com.ruoyi.platform.grpcB\nTrainProtoP\001" +
      "\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_WlossRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_WlossRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_WlossRequest_descriptor,
        new String[] { "Id", });
    internal_static_proto_StepRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_StepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StepRequest_descriptor,
        new String[] { "Id", });
    internal_static_proto_TeacheraccRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_TeacheraccRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TeacheraccRequest_descriptor,
        new String[] { "Id", });
    internal_static_proto_StepResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_StepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StepResponse_descriptor,
        new String[] { "Step", });
    internal_static_proto_WlossResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_WlossResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_WlossResponse_descriptor,
        new String[] { "Step", "Wloss", });
    internal_static_proto_TeacheraccResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_TeacheraccResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TeacheraccResponse_descriptor,
        new String[] { "Step", "Maxacc", "Minacc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
