# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrain.proto\x12\x05proto\"\x1a\n\x0cWlossRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\x0bStepRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11TeacheraccRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0cStepResponse\x12\x0c\n\x04step\x18\x01 \x03(\x05\",\n\rWlossResponse\x12\x0c\n\x04step\x18\x01 \x03(\x05\x12\r\n\x05wloss\x18\x02 \x03(\x01\"B\n\x12TeacheraccResponse\x12\x0c\n\x04step\x18\x01 \x03(\x05\x12\x0e\n\x06maxacc\x18\x02 \x03(\x01\x12\x0e\n\x06minacc\x18\x03 \x03(\x01\x32\xb8\x01\n\x05Train\x12\x32\n\x07GetStep\x12\x12.proto.StepRequest\x1a\x13.proto.StepResponse\x12\x35\n\x08GetWloss\x12\x13.proto.WlossRequest\x1a\x14.proto.WlossResponse\x12\x44\n\rGetTeacheracc\x12\x18.proto.TeacheraccRequest\x1a\x19.proto.TeacheraccResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'train_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WLOSSREQUEST._serialized_start=22
  _WLOSSREQUEST._serialized_end=48
  _STEPREQUEST._serialized_start=50
  _STEPREQUEST._serialized_end=75
  _TEACHERACCREQUEST._serialized_start=77
  _TEACHERACCREQUEST._serialized_end=108
  _STEPRESPONSE._serialized_start=110
  _STEPRESPONSE._serialized_end=138
  _WLOSSRESPONSE._serialized_start=140
  _WLOSSRESPONSE._serialized_end=184
  _TEACHERACCRESPONSE._serialized_start=186
  _TEACHERACCRESPONSE._serialized_end=252
  _TRAIN._serialized_start=255
  _TRAIN._serialized_end=439
# @@protoc_insertion_point(module_scope)
