# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import train_pb2 as train__pb2


class TrainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStep = channel.unary_unary(
                '/proto.Train/GetStep',
                request_serializer=train__pb2.StepRequest.SerializeToString,
                response_deserializer=train__pb2.StepResponse.FromString,
                )
        self.GetWloss = channel.unary_unary(
                '/proto.Train/GetWloss',
                request_serializer=train__pb2.WlossRequest.SerializeToString,
                response_deserializer=train__pb2.WlossResponse.FromString,
                )
        self.GetTeacheracc = channel.unary_unary(
                '/proto.Train/GetTeacheracc',
                request_serializer=train__pb2.TeacheraccRequest.SerializeToString,
                response_deserializer=train__pb2.TeacheraccResponse.FromString,
                )


class TrainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWloss(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeacheracc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStep': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStep,
                    request_deserializer=train__pb2.StepRequest.FromString,
                    response_serializer=train__pb2.StepResponse.SerializeToString,
            ),
            'GetWloss': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWloss,
                    request_deserializer=train__pb2.WlossRequest.FromString,
                    response_serializer=train__pb2.WlossResponse.SerializeToString,
            ),
            'GetTeacheracc': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeacheracc,
                    request_deserializer=train__pb2.TeacheraccRequest.FromString,
                    response_serializer=train__pb2.TeacheraccResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Train', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Train(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Train/GetStep',
            train__pb2.StepRequest.SerializeToString,
            train__pb2.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWloss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Train/GetWloss',
            train__pb2.WlossRequest.SerializeToString,
            train__pb2.WlossResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTeacheracc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Train/GetTeacheracc',
            train__pb2.TeacheraccRequest.SerializeToString,
            train__pb2.TeacheraccResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
